### ISSUE TITLE
Steam is disconnecting us and reconnecting seemingly randomly after several hours of running consistently.

### ISSUE THREAD

**Issue by vBubbaa** [vBubbaa/django-steamkit-integration#10]
While using the [Steam](Steam Package) to track changes from Steam and get app information to process apps for our database, we are running into a problem of getting disconnected from the Steam Client, and then once it reconnects each response is returning empty. I have a hunch that it is due to us using two difference Client Connections running parallel. 

Currently, we are running one Client to scan for Steam changes using [get_changes_since()](https://steam.readthedocs.io/en/latest/api/steam.client.builtins.html#steam.client.builtins.apps.Apps.get_changes_since), and one client for processing apps and getting their information from [get_product_info()](https://steam.readthedocs.io/en/latest/api/steam.client.builtins.html#steam.client.builtins.apps.Apps.get_product_info). We may will need to try and run both of these off of the same Client instance and see if that fixed our disconnect issue.

Stacktrace of ClientUpdater() failing:
```Disconnected.
Reconnecting...
Connected to %s ('205.196.6.67', 27018)
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/env/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/env/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/game/management/commands/ClientUpdater.py", line 35, in handle
    changes = worker.get_product_changes(currentChangeNum)
  File "/utils/client.py", line 116, in get_product_changes
    return proto_to_dict(resp) or {}
  File "env/lib/python3.7/site-packages/steam/utils/proto.py", line 51, in proto_to_dict
    raise TypeError("Expected `message` to be a instance of protobuf message")
TypeError: Expected `message` to be a instance of protobuf message
```

As shown in the stacktrace, after we reconnect from a disconnect, Steam returns empty responses with no data.

**Comment by vBubbaa** [comment]
As of now, https://github.com/vBubbaa/django-steamkit-integration/commit/c2c92a83c37f7ea62c90f67687aef1a3f4e4c7ed has fixed the issue. I believe the issue had to do with running 2 clients in parallel. After switching to only one client connection the updating has been running smoothly with no issues.

I will reopen this issue, if we happen to experience the same problem later down the line.
